### PR TITLE
Fix XML rewriting

### PR DESCRIPTION
**Pull request by xiaodoudou**
This simple fix avoid cheerio to rewrite the DOM of the SVG when namespace are in use like xmlns-xlink.

### CODE REVIEW

**Comment by xiaodoudou** [comment]
Let me know if you need me to implement into the current example, a case cover by that change (i.e. svg that use xlink href)
Cheers

**Comment by xiaodoudou** [comment]
Did add a check if any directive exist it will be commented on the destination

**Comment by xiaodoudou** [comment]
Did refactor the code to avoid xmlMode to break html files when some elements are not properly closed like  vs  or even the fact that it try to refactor empty DOM tags.

Please review the change and let me know if improvement are needed.

**Comment by viktorlarsson** [comment]
Thanks for the help! Merged into master now :)

**Pull request merged**
